/**
 * Winget Source Proxy Worker — Microsoft.Rest mode
 *
 * Implements a Microsoft.Rest winget source backed by the microsoft/winget-pkgs
 * GitHub repository. Rewrites InstallerUrl values to proxy through this worker
 * so all installer downloads are accelerated (no manifest hash issue — REST
 * sources do not SHA256-verify manifest content).
 *
 * REST API endpoints (for Microsoft.Rest source type):
 *   GET  /information             → source metadata
 *   POST /manifestSearch          → package search (exact ID + keyword)
 *   GET  /packageManifests/{id}   → package manifest with rewritten InstallerUrl
 *
 * Generic installer downloads are NOT proxied: InstallerUrl values are rewritten
 * to the MIRROR and the client fetches them from the mirror directly.
 *
 * Usage:
 *   winget source add --name winget-cn \
 *     --arg https://<your-worker-subdomain>.workers.dev \
 *     --type Microsoft.Rest
 *
 * Configure the installer mirror via the MIRROR env var (wrangler.toml [vars]
 * or a secret). It must accept the path form:
 *   <MIRROR>/https://github.com/owner/repo/...
 * e.g. https://gh-proxy.org
 */
import * as jsyaml from "js-yaml";

// ─── Constants ───────────────────────────────────────────────────────────────

// YAML manifest files. Prefer jsDelivr's CDN (cdn.jsdelivr.net/gh/...@master):
// it is purpose-built for serving repo files, has a global edge cache, and — unlike
// raw.githubusercontent.com — does NOT rate-limit Cloudflare Workers' shared egress
// IPs. A transient 429 from raw.githubusercontent previously returned an empty body
// that the cf cache then pinned for an hour, producing manifests with Installers:[]
// (winget install dies with 0x8a150039). We only fall back to raw.githubusercontent
// if jsDelivr is unreachable.
const JSDLV_MANIFEST_BASE = "https://cdn.jsdelivr.net/gh/microsoft/winget-pkgs@master";
const RAW_MANIFEST_BASE = "https://raw.githubusercontent.com/microsoft/winget-pkgs/master";

// ─── Environment ─────────────────────────────────────────────────────────────

interface Env {
  GITHUB_TOKEN?: string;
  // Mirror used for GitHub-hosted installers, e.g. https://gh-proxy.org
  // Must accept the path form: <MIRROR>/https://github.com/owner/repo/...
  MIRROR?: string;
  // Prebuilt full package index (id + latest version), generated by the
  // build-index Action and served from this repo. Enables complete keyword
  // search without per-query GitHub API calls.
  INDEX_URL?: string;
}

// ─── HTTP helpers ────────────────────────────────────────────────────────────

// Rewrite only GitHub-hosted installer URLs to go through a ghproxy-style
// mirror. Non-GitHub installers keep their original URL (winget downloads them
// directly). The mirror is expected to accept the path form:
//   <MIRROR>/https://github.com/owner/repo/...
// so the client fetches the installer from the mirror, NOT through this worker.
function rewriteInstallerUrl(url: string, mirror: string): string {
  if (!url) return url;
  try {
    const u = new URL(url);
    const isGitHub =
      /github\.com$/.test(u.host) || /githubusercontent\.com$/.test(u.host);
    if (isGitHub) {
      return `${mirror.replace(/\/+$/, "")}/${u.protocol}//${u.host}${u.pathname}${u.search}`;
    }
  } catch { /* leave as-is */ }
  return url;
}

// ─── Manifest file fetch ──────────────────────────────────────────────────────
// Nothing in this Worker talks to api.github.com: package discovery comes from
// the prebuilt index, and manifest bodies come from the two static hosts below.
// That is deliberate — the Contents API allows 60 requests/hour per IP and
// Cloudflare's egress IPs are shared with every other worker on them, so any
// code path that could reach it is a path to a 403 for all users at once.

// One manifest file, three possible outcomes. They must stay distinguishable:
// a 404 means the package does not have that file, while a 5xx or a thrown fetch
// (jsDelivr building a cold path can exceed its own limit) means we could not
// tell. Collapsing the two into "absent" makes a CDN outage look like a package
// that does not exist, which is the ambiguity this Worker keeps having to avoid.
type FileFetch =
  | { body: string }
  | { missing: true }
  | { error: string };

// Fetch one manifest file from one host. Error/empty responses are never
// edge-cached (cacheTtlByStatus 400-599:0) so a transient upstream failure can't
// be pinned for an hour like it could with a fixed cacheTtl.
async function fetchFromHost(
  host: string,
  versionPath: string,
  filename: string
): Promise<FileFetch> {
  const url = `${host}/${versionPath}/${filename}`;
  try {
    const r = await fetch(url, {
      headers: { "User-Agent": "winget-cn-proxy/2.0" },
      // @ts-ignore — CF Workers cf option for edge caching.
      cf: {
        cacheEverything: true,
        cacheTtlByStatus: { "200-299": 3600, "400-599": 0 },
      },
    });
    if (r.status === 404) return { missing: true };
    if (!r.ok) return { error: `${r.status} from ${host}` };
    const t = await r.text();
    // jsDelivr answers some failures with an empty 200; an empty manifest is not
    // a manifest, so it counts as absent rather than as content to parse.
    if (!t.trim().length) return { missing: true };
    return { body: t };
  } catch (e) {
    return { error: `fetch threw: ${String((e as Error)?.message ?? e)}` };
  }
}

const MANIFEST_HOSTS = [JSDLV_MANIFEST_BASE, RAW_MANIFEST_BASE];

// Fetch a manifest YAML file, trying jsDelivr first then raw.githubusercontent.
// A host that fails does not end the lookup — the other one may well have it —
// but if none of them served the file, a failure outranks a 404: we report that
// we could not tell rather than that the file is not there.
async function fetchManifestFile(
  versionPath: string,
  filename: string
): Promise<FileFetch> {
  let last: FileFetch = { missing: true };
  for (const host of MANIFEST_HOSTS) {
    const result = await fetchFromHost(host, versionPath, filename);
    if ("body" in result) return result;
    if ("error" in result) last = result;
  }
  return last;
}

// ─── Package ID helpers ───────────────────────────────────────────────────────

interface PkgPath {
  firstLetter: string;
  publisher: string;
  packageRest: string;
  basePath: string; // e.g. "manifests/s/SublimeHQ/SublimeText.4"
}

function parsePackageId(id: string): PkgPath {
  const firstLetter = id[0].toLowerCase();
  const dot = id.indexOf(".");
  const publisher = dot >= 0 ? id.slice(0, dot) : id;
  const packageRest = dot >= 0 ? id.slice(dot + 1) : "";
  // Directory path: all dots in the package portion become slashes
  // e.g. SublimeHQ.SublimeText.4 → manifests/s/SublimeHQ/SublimeText/4
  const packageDirPath = packageRest.replace(/\./g, "/");
  return {
    firstLetter,
    publisher,
    packageRest,
    basePath: `manifests/${firstLetter}/${publisher}/${packageDirPath}`,
  };
}

// ─── REST API: GET /information ───────────────────────────────────────────────

function handleInformation(): Response {
  return Response.json({
    Data: {
      SourceIdentifier: "winget-cn",
      ServerSupportedVersions: ["1.0.0", "1.1.0", "1.6.0"],
    },
  });
}

// ─── Keyword search ─────────────────────────────────────────────────────────
// The prebuilt index (INDEX_URL) is the only discovery source. It is generated
// from the SQLite database inside source2.msix — the package winget downloads
// for its own default source — so each entry carries the fields Microsoft's
// ingest already resolved: id, latest version, display name, moniker and tags.
// A keyword that matches nothing in it returns nothing; guessing otherwise
// would mean the GitHub Contents API, which is capped at 60 requests/hour per
// IP and Cloudflare's egress IPs are shared, so a single burst of failed calls
// degrades the source for every user on that IP at once.
//
// Known gap, accepted deliberately: this feed lags winget-pkgs a little in both
// directions, so a just-published package can be invisible until the next build.

// One index line: `{"id":..,"v":..,"n":..}` plus optional `m` (moniker) and `t`
// (tags). 15310 packages, all of them named; 5940 (39%) have a moniker and 11496
// (75%) have tags, so those two are genuinely optional, not defensively typed.
type IndexEntry = { id: string; v: string; n?: string; m?: string; t?: string[] };

// Module-level memo of the parsed index, so a refresh costs one request per
// interval rather than one per search.
// A failure is not swallowed: indexCache stays null, every later query retries,
// and the reason is logged. The old `catch { return indexCache?.data ?? null }`
// plus a silent `!resp.ok` turn produced 200 `{"Data":[]}` responses forever
// after one bad fetch, which looks exactly like "no such package" to winget and
// is impossible to tell apart from the dashboard.
let indexCache: { data: IndexEntry[]; at: number } | null = null;

async function getIndex(
  env: Env,
  opts: { force?: boolean } = {}
): Promise<IndexEntry[] | null> {
  if (!env.INDEX_URL) {
    console.log("getIndex: INDEX_URL is not configured, search has no data source");
    return null;
  }
  const now = Date.now();
  if (!opts.force && indexCache && now - indexCache.at < 300_000) return indexCache.data;
  try {
    const resp = await fetch(env.INDEX_URL, {
      headers: { "User-Agent": "winget-cn-proxy/2.0" },
      cf: { cacheEverything: true, cacheTtl: 300 },
    });
    const text = await resp.text();
    if (!resp.ok) {
      console.log(`getIndex: ${resp.status} from ${env.INDEX_URL} (${text.length} bytes), searching without an index`);
      return null;
    }
    const data = text
      .split("\n")
      .filter((l) => l.trim().length > 0)
      .map((l) => JSON.parse(l) as IndexEntry);
    if (!data.length) {
      console.log(`getIndex: empty body from ${env.INDEX_URL}, searching without an index`);
      return null;
    }
    indexCache = { data, at: now };
    return data;
  } catch (e) {
    console.log(`getIndex: fetch threw ${e instanceof Error ? e.message : String(e)}, searching without an index`);
    return null;
  }
}

// The name winget shows. The index carries the real PackageName; the fallback
// only covers a package the official feed left unnamed.
const displayName = (e: IndexEntry) => e.n ?? e.id.split(".").slice(1).join(" ");

// Return a search Data entry for a PackageIdentifier, from the prebuilt index
// only. The index knows the package exists and its latest version, which is all
// winget needs to go on and fetch a manifest. A package absent from the index
// was published after the last rebuild and is reported as not found: guessing it
// would mean the rate-limited Contents API, which is worse than a miss.
async function lookupPackageId(
  id: string,
  env: Env,
  requestedVersion?: string | null
): Promise<object | null> {
  const { publisher } = parsePackageId(id);
  const index = await getIndex(env);
  const hit =
    index?.find((e) => e.id === id) ??
    index?.find((e) => e.id.toLowerCase() === id.toLowerCase());
  if (!hit?.v) return null;
  const versions = [hit.v];
  if (requestedVersion && requestedVersion !== hit.v) versions.push(requestedVersion);
  return {
    PackageIdentifier: hit.id,
    PackageName: displayName(hit),
    Publisher: publisher,
    Versions: versions.map((v) => ({ PackageVersion: v })),
  };
}

// Search results only need the four fields winget's deserializer requires; the
// full display metadata comes later from /packageManifests.
function toSearchResults(matched: IndexEntry[]): object[] {
  const out: object[] = [];
  for (const e of matched) {
    out.push({
      PackageIdentifier: e.id,
      PackageName: displayName(e),
      Publisher: e.id.split(".")[0],
      Versions: [{ PackageVersion: e.v }],
    });
  }
  return out;
}

// How well a field matched decides the rank (exact beats prefix beats
// substring); the field only breaks ties (id beats moniker beats name beats
// tag). Quality first is what the client-side search does too: an exact hit on
// any field is a better answer than a loose hit, so `vscode` returns
// Microsoft.VisualStudioCode (moniker exactly equal) ahead of
// JonahFintzDEV.CommandPalette-VSCode (id merely contains it).
// The 匹配 column, though, is not ours to control: a Microsoft.Rest search
// result carries no manifest (SearchResponseDeserializer_1_0.cpp:163 leaves
// VersionInfo::Manifest empty), so the client's FindBestMatchCriteria can only
// ever consult Id/Name and the system reference strings it was given. Moniker,
// Command and Tag live in the manifest's localization sections and are empty for
// every REST hit — so a moniker/tag row prints "UnknownMatchField:" here, where
// the preindexed official source prints "Tag: sqlite3" because its own query
// knows the column. Id/Name hits print blank on both (WorkflowBase.cpp:38).
// Ranking and the result set are unaffected; only that one column differs.
const F_ID = 0;
const F_MONIKER = 1;
const F_NAME = 2;
const F_TAG = 3;
const Q_EXACT = 0;
const Q_PREFIX = 1;
const Q_SUBSTRING = 2;

// Quality of a single field value against the keyword; null when it does not match.
function matchQuality(value: string | undefined, kw: string): number | null {
  if (!value) return null;
  const v = value.toLowerCase();
  if (v === kw) return Q_EXACT;
  if (v.startsWith(kw)) return Q_PREFIX;
  if (v.includes(kw)) return Q_SUBSTRING;
  return null;
}

async function keywordSearch(keyword: string, env: Env): Promise<object[]> {
  const kw = keyword.toLowerCase().trim();
  if (!kw) return [];

  const index = await getIndex(env);
  if (!index || !index.length) {
    console.log(`keywordSearch: no index available for "${keyword}"`);
    return [];
  }

  // winget normalizes away punctuation when it asks for
  // NormalizedPackageNameAndPublisher, so an exact match on the normalized id is
  // a real answer to a real query shape ("ytdlpffmpeg" for yt-dlp.FFmpeg). Exact
  // only: substring matching on a normalized id would accept hits spanning a dot
  // that no client-side comparison can reproduce.
  const nkw = normalizeTerm(kw);

  const best = new Map<string, { e: IndexEntry; p: number; t: number }>();
  for (const e of index) {
    if (!e.v) continue; // never emit empty Versions — winget rejects it (0x8a150039)

    let p = -1;
    let t = 0;
    const consider = (field: number, value: string | undefined) => {
      const q = matchQuality(value, kw);
      if (q === null) return;
      const rank = q * 4 + field;
      if (p < 0 || rank < p || (rank === p && (value?.length ?? 0) < t)) {
        p = rank;
        t = value?.length ?? 0;
      }
    };
    consider(F_ID, e.id);
    consider(F_MONIKER, e.m);
    consider(F_NAME, e.n);
    for (const tag of e.t ?? []) consider(F_TAG, tag);
    if (p < 0 && nkw && normalizeTerm(e.id) === nkw) {
      p = Q_EXACT * 4 + F_ID;
      t = e.id.length;
    }
    if (p < 0) continue;

    const cur = best.get(e.id);
    if (!cur || p < cur.p || (p === cur.p && t < cur.t)) best.set(e.id, { e, p, t });
  }

  if (!best.size) {
    // The index is the only discovery source. Reaching here means the keyword
    // matches nothing in the feed as of the last rebuild; that is reported as an
    // empty result rather than guessed at via the GitHub API.
    console.log(`keywordSearch: no index match for "${keyword}"`);
    return [];
  }

  // All matches are returned, ranked. The official feed behaves the same way
  // (`winget search e -s winget` returns 14468 rows), and dropping the tail
  // would silently hide packages a user can otherwise find.
  const ranked = [...best.values()].sort(
    (a, b) => a.p - b.p || a.t - b.t || a.e.id.localeCompare(b.e.id)
  );
  console.log(`keywordSearch: index hit, returned=${ranked.length} for "${keyword}"`);
  return toSearchResults(ranked.map((r) => r.e));
}

// winget's ProductCode is "<PackageIdentifier>_<sourceId>", e.g.
// "yt-dlp.yt-dlp_microsoft.winget.source_8wekyb3d8bbwe". The source id is the
// source that *declared* the dependency (the official one), so for dependency
// resolution it is meaningless to us. Strip it to recover the bare
// PackageIdentifier we can look up directly.
function stripProductCodeSuffix(kw: string): string {
  const known = kw.lastIndexOf("_microsoft.winget.source_");
  if (known > 0) return kw.slice(0, known);
  // Generic fallback: "<id.with.dot>_<sourceToken>"
  const m = kw.match(/^([A-Za-z0-9.-]+\.[A-Za-z0-9.-]+?)_[A-Za-z0-9._-]+$/);
  if (m) return m[1];
  return kw;
}

// Normalize a search term the way winget normalizes PackageName/Publisher for
// the NormalizedPackageNameAndPublisher match field: lowercase, drop every
// non-alphanumeric char ("yt-dlp" -> "ytdlp").
function normalizeTerm(s: string): string {
  return (s ?? "").toLowerCase().replace(/[^a-z0-9]/g, "");
}

// ─── REST API: POST /manifestSearch ──────────────────────────────────────────

async function handleManifestSearch(
  request: Request,
  env: Env
): Promise<Response> {
  let body: any;
  try {
    body = await request.json();
  } catch {
    return Response.json({ Data: [] });
  }

  // Debug: log exact request body from winget
  console.log("manifestSearch body:", JSON.stringify(body));

  const filters: any[] = body?.Filters ?? [];
  const inclusions: any[] = body?.Inclusions ?? [];
  const query = body?.Query;

  // ── Case 0: dependency resolution (ProductCode) ────────────────────────────
  // When winget resolves a package's dependencies it queries every source by
  // ProductCode ("<id>_microsoft.winget.source_8wekyb3d8bbwe") and by
  // NormalizedPackageNameAndPublisher. Our index is keyed by PackageIdentifier,
  // so strip the ProductCode source suffix to recover the exact id and look it
  // up directly. This makes dependency search hit instead of returning empty.
  const productCode = inclusions.find(
    (f) => f.PackageMatchField === "ProductCode"
  )?.RequestMatch?.KeyWord;
  if (productCode) {
    // winget LOWERCASES the PackageIdentifier inside a ProductCode, while the
    // GitHub directory path is case-sensitive ("yt-dlp.FFmpeg" not "...ffmpeg").
    // lookupPackageId resolves the canonical casing from the index.
    const rawId = stripProductCodeSuffix(productCode);
    console.log("manifestSearch: productCode -> id:", productCode, "->", rawId);
    if (rawId && rawId.includes(".")) {
      const entry = await lookupPackageId(rawId, env);
      if (entry) {
        const result = { Data: [entry] };
        console.log("manifestSearch response (productCode):", JSON.stringify(result));
        return Response.json(result);
      }
    }
  }

  // ── Case 1: PackageIdentifier filter/inclusion ───────────────────────────
  // Only treat as a real id lookup when the value contains a dot. winget
  // sometimes sends a bare keyword (e.g. "HandBrake") under the
  // PackageIdentifier match field; parsing that as an id yields an empty
  // PackageName and a bogus basePath, making winget reject the whole search
  // (0x8a150039 "Missing required package fields").
  const allCriteria = [...filters, ...inclusions];
  const idFilter = allCriteria.find(
    (f) =>
      f.PackageMatchField === "PackageIdentifier" &&
      (f.RequestMatch?.MatchType === "Exact" ||
        f.RequestMatch?.MatchType === "CaseInsensitive") &&
      (f.RequestMatch?.KeyWord ?? "").includes(".")
  );
  if (idFilter) {
    const id: string = idFilter.RequestMatch.KeyWord;
    console.log("manifestSearch: looking up package id:", id);
    const entry = await lookupPackageId(id, env);
    if (entry) {
      const result = { Data: [entry] };
      console.log("manifestSearch response:", JSON.stringify(result));
      return Response.json(result);
    }
    // Not found (or rate-limited) -> fall through to keyword search below.
  }

  // ── Case 2: keyword search ───────────────────────────────────────────────
  // winget's `upgrade <word>` sends the term as name-like Inclusions
  // (PackageName / Moniker / Publisher / PackageIdentifier) rather than a Query.
  const keyword: string | undefined =
    query?.KeyWord ??
    allCriteria.find(
      (c) =>
        [
          "PackageName",
          "Moniker",
          "Publisher",
          "PackageIdentifier",
          "NormalizedPackageNameAndPublisher",
        ].includes(c.PackageMatchField) && c.RequestMatch?.KeyWord
    )?.RequestMatch?.KeyWord;
  if (keyword) {
    // If keyword looks like a PackageIdentifier (Publisher.Package), try direct lookup first
    if (/^[A-Za-z0-9_-]+\.[A-Za-z0-9._-]+$/.test(keyword)) {
      const entry = await lookupPackageId(keyword, env);
      if (entry) {
        return Response.json({ Data: [entry] });
      }
    }

    // Keyword search over the prebuilt index. (GitHub code search is
    // unreliable for winget-pkgs, so we don't use it.)
    const results = await keywordSearch(keyword, env);
    if (results.length) {
      return Response.json({ Data: results });
    }
  }

  console.log("manifestSearch: no results (empty Data)");
  return Response.json({ Data: [] });
}

// ─── REST API: GET /packageManifests/{id}[/{version}] ────────────────────────

async function handlePackageManifest(
  id: string,
  requestedVersion: string | null,
  mirror: string,
  env: Env
): Promise<Response> {
  const { publisher, basePath } = parsePackageId(id);

  let version: string;
  if (requestedVersion) {
    version = requestedVersion;
  } else {
    // Resolve the latest version from the index. No index entry means no
    // version to ask for, so this fails rather than enumerating the package
    // directory through the rate-limited GitHub API.
    const index = await getIndex(env);
    const hit =
      index?.find((e) => e.id === id) ??
      index?.find((e) => e.id.toLowerCase() === id.toLowerCase());
    if (!hit?.v) {
      return Response.json(
        { ErrorCode: 404, ErrorMessage: `Not in index: ${id}` },
        { status: 404 }
      );
    }
    version = hit.v;
  }

  const versionPath = `${basePath}/${version}`;

  const parseYaml = (body: string): any => {
    try {
      return (jsyaml.load(body) as any) ?? {};
    } catch {
      return {};
    }
  };

  // A manifest we cannot assemble is reported, not padded with empty fields.
  // `missingStatus` is what to say when a host plainly does not have the file:
  // 404 for the version and installer manifests (that package is not here), 502
  // for a locale the version manifest promises but nobody serves (the package
  // does exist; the upstream state is broken). A failed request is always 502 —
  // it is not evidence of absence.
  const fileFailed = (
    result: { missing: true } | { error: string },
    filename: string,
    missingStatus: 404 | 502
  ): Response => {
    const status = "error" in result ? 502 : missingStatus;
    const detail = "error" in result ? result.error : `not served by ${MANIFEST_HOSTS.join(" or ")}`;
    console.log(`packageManifests: ${filename} for ${id}@${version}: ${detail}`);
    return Response.json(
      { ErrorCode: status, ErrorMessage: `${filename} for ${id}@${version}: ${detail}` },
      { status }
    );
  };

  // Every version directory in winget-pkgs has a `{id}.yaml` that says which
  // layout it uses: `ManifestType: version` (three files, with the default
  // locale's tag in its `DefaultLocale` field) or `ManifestType: merged` (one
  // file, locale inline). Asking it is one small request and beats guessing the
  // tag: a package whose default locale is zh-CN usually *does* have a
  // `{id}.locale.en-US.yaml`, but that is an additional localization
  // (`ManifestType: locale`), which is not allowed to carry PackageName — using
  // it as the default produced manifests we then had to refuse.
  const versionFile = await fetchManifestFile(versionPath, `${id}.yaml`);
  if (!("body" in versionFile)) return fileFailed(versionFile, `${id}.yaml`, 404);
  const rootDoc = parseYaml(versionFile.body);

  // The locale a REST manifest must return is the package's default one, and it
  // has to satisfy the schema's required fields (PackageName, License,
  // ShortDescription, Publisher).
  let installerDoc: any;
  let localeDoc: any;

  if (rootDoc.ManifestType === "merged") {
    installerDoc = rootDoc;
    localeDoc = rootDoc;
  } else if (rootDoc.ManifestType === "version") {
    if (!rootDoc.DefaultLocale) {
      console.log(`packageManifests: version manifest has no DefaultLocale for ${id}@${version}`);
      return Response.json(
        { ErrorCode: 502, ErrorMessage: `No default locale declared for ${id}@${version}` },
        { status: 502 }
      );
    }
    const [installerFile, localeFile] = await Promise.all([
      fetchManifestFile(versionPath, `${id}.installer.yaml`),
      fetchManifestFile(versionPath, `${id}.locale.${rootDoc.DefaultLocale}.yaml`),
    ]);
    if (!("body" in installerFile)) return fileFailed(installerFile, `${id}.installer.yaml`, 404);
    if (!("body" in localeFile)) {
      return fileFailed(localeFile, `${id}.locale.${rootDoc.DefaultLocale}.yaml`, 502);
    }
    installerDoc = parseYaml(installerFile.body);
    localeDoc = parseYaml(localeFile.body);
  } else {
    console.log(`packageManifests: unexpected manifest layout for ${id}@${version} (ManifestType=${rootDoc.ManifestType})`);
    return Response.json(
      { ErrorCode: 502, ErrorMessage: `Unexpected version manifest for ${id}@${version}` },
      { status: 502 }
    );
  }

  // winget validates the assembled manifest before it will show or install
  // anything (Interface.cpp:290 throws APPINSTALLER_CLI_ERROR_RESTSOURCE_INVALID_DATA
  // on any error), so a DefaultLocale missing PackageName or License would fail
  // as 0x8a150039 for the whole source rather than for this one package.
  if (!localeDoc.PackageName || !localeDoc.License) {
    console.log(`packageManifests: incomplete default locale for ${id}@${version}`);
    return Response.json(
      {
        ErrorCode: 502,
        ErrorMessage: `Incomplete default locale manifest for ${id}@${version}`,
      },
      { status: 502 }
    );
  }

  // Build installers list with rewritten InstallerUrl
  const rawInstallers: any[] = Array.isArray(installerDoc.Installers)
    ? installerDoc.Installers
    : [];

  // Package-level InstallerType / NestedInstallerType / Dependencies must be
  // propagated to each installer. winget-pkgs stores these at the package level
  // (root of the installer YAML), while each installer entry often omits them;
  // winget's REST deserializer requires InstallerType on every installer and
  // surfaces Dependencies (e.g. "依赖项") from the installer object.
  const installers = rawInstallers.map((inst) => {
    const out: any = { ...inst };
    if (!out.InstallerType && installerDoc.InstallerType) {
      out.InstallerType = installerDoc.InstallerType;
    }
    if (!out.NestedInstallerType && installerDoc.NestedInstallerType) {
      out.NestedInstallerType = installerDoc.NestedInstallerType;
    }
    if (!out.Dependencies && installerDoc.Dependencies) {
      out.Dependencies = installerDoc.Dependencies;
    }
    if (out.InstallerUrl) {
      out.InstallerUrl = rewriteInstallerUrl(out.InstallerUrl, mirror);
    }
    return out;
  });

  // Build DefaultLocale by transparently passing through every field from the
  // manifest's locale YAML (Moniker, Author, PublisherSupportUrl, PrivacyUrl,
  // PackageUrl, Tags, ReleaseNotes, ReleaseNotesUrl, Documentations, Agreements,
  // Description, ...). The winget REST DefaultLocale schema accepts these as
  // optional members; only a hardcoded subset was mapped before, which is why
  // `winget show` looked sparse next to the official source. Drop the keys that
  // belong to the surrounding document rather than to its locale — including the
  // installer keys, because a merged manifest doubles as the locale source.
  const LOCALE_OMIT = new Set([
    "PackageIdentifier",
    "PackageVersion",
    "ManifestType",
    "ManifestVersion",
    "Installers",
    "InstallerLocale",
    "Locales",
    "DisplayWarnings",
    "InstallerType",
    "NestedInstallerType",
    "Dependencies",
    "MinimumOSVersion",
    "ReleaseDate",
  ]);
  const defaultLocale: any = { PackageLocale: localeDoc.PackageLocale };
  for (const [k, v] of Object.entries(localeDoc)) {
    if (!LOCALE_OMIT.has(k)) defaultLocale[k] = v;
  }

  return Response.json({
    Data: {
      PackageIdentifier: id,
      // winget's Microsoft.Rest packageManifest contract requires PackageName
      // and Publisher at the top-level Data object (not only inside
      // DefaultLocale). Omitting them makes winget reject the whole manifest
      // with 0x8a150039 "REST source returned invalid data".
      PackageName: localeDoc.PackageName,
      Publisher: localeDoc.Publisher ?? publisher,
      ShortDescription: localeDoc.ShortDescription ?? "",
      Versions: [
        {
          PackageVersion: version,
          DefaultLocale: defaultLocale,
          Installers: installers,
          Locales: [],
        },
      ],
    },
  });
}

// ─── Landing page ─────────────────────────────────────────────────────────────

function landingPage(host: string, mirror: string): Response {
  const html = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Winget 镜像代理</title>
<style>
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  :root {
    --bg: #0d1117; --surface: #161b22; --card: #21262d; --border: #30363d;
    --text: #e6edf3; --muted: #8b949e; --accent: #58a6ff;
    --green: #3fb950; --yellow: #e3b341; --radius: 8px;
  }
  body { background: var(--bg); color: var(--text); font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; min-height: 100vh; padding: 2rem 1rem; }
  .container { max-width: 860px; margin: 0 auto; }
  header { text-align: center; padding: 2rem 0 2.5rem; }
  header h1 { font-size: 2rem; font-weight: 700; display: flex; align-items: center; justify-content: center; gap: .6rem; }
  header p { color: var(--muted); margin-top: .6rem; font-size: .95rem; }
  .badge-row { display: flex; gap: .75rem; flex-wrap: wrap; justify-content: center; margin-top: .75rem; font-size: .85rem; }
  .badge { background: var(--card); border: 1px solid var(--border); border-radius: 6px; padding: .3rem .75rem; }
  .card { background: var(--surface); border: 1px solid var(--border); border-radius: var(--radius); padding: 1.5rem; margin-bottom: 1.5rem; }
  .card h2 { font-size: 1rem; font-weight: 600; margin-bottom: 1rem; color: var(--accent); }
  .steps { display: flex; flex-direction: column; gap: .75rem; }
  .step { display: flex; gap: .75rem; }
  .step-num { width: 22px; height: 22px; border-radius: 50%; background: rgba(88,166,255,.2); color: var(--accent); font-size: .75rem; font-weight: 700; display: flex; align-items: center; justify-content: center; flex-shrink: 0; margin-top: 2px; }
  .step-body { flex: 1; }
  .step-body p { font-size: .875rem; color: var(--muted); margin-bottom: .4rem; }
  .code-block { background: var(--bg); border: 1px solid var(--border); border-radius: 6px; padding: .65rem .9rem; font-family: "SFMono-Regular", Consolas, monospace; font-size: .82rem; display: flex; gap: .5rem; align-items: flex-start; }
  .code-block pre { flex: 1; margin: 0; white-space: pre-wrap; word-break: break-all; color: var(--green); }
  .btn { background: transparent; color: var(--muted); border: 1px solid var(--border); border-radius: 6px; padding: .35rem .75rem; font-size: .8rem; cursor: pointer; white-space: nowrap; }
  .btn:hover { color: var(--accent); border-color: var(--accent); }
  .note { font-size: .78rem; color: var(--muted); margin-top: .4rem; }
  .alert { background: rgba(255,166,0,.08); border: 1px solid rgba(255,166,0,.3); border-radius: 6px; padding: .65rem .9rem; font-size: .85rem; color: var(--yellow); margin-bottom: 1rem; }
  table { width: 100%; border-collapse: collapse; font-size: .875rem; }
  th { text-align: left; color: var(--muted); font-weight: 500; padding: .5rem .75rem; border-bottom: 1px solid var(--border); }
  td { padding: .55rem .75rem; border-bottom: 1px solid var(--border); }
  tr:last-child td { border-bottom: none; }
  code { background: rgba(110,118,129,.15); border-radius: 4px; padding: .15em .45em; font-family: "SFMono-Regular", Consolas, monospace; font-size: .85em; }
  footer { text-align: center; color: var(--muted); font-size: .8rem; padding: 2rem 0 1rem; }
  footer a { color: var(--accent); text-decoration: none; }
</style>
</head>
<body>
<div class="container">
  <header>
    <h1>📦 Winget 镜像代理</h1>
    <p>基于 Cloudflare Workers 的自建 winget 源（Microsoft.Rest）· 自动将 GitHub 安装包地址改写为国内镜像（gh-proxy 等），安装器由客户端直连镜像下载，国内拉取飞快。</p>
    <div class="badge-row">
      <span class="badge">🌐 镜像源地址：<code>${host}</code></span>
      <span class="badge">🇨🇳 安装器镜像：<code>${mirror}</code></span>
    </div>
  </header>

  <!-- Quick Start -->
  <div class="card">
    <h2>🚀 快速开始（推荐：Microsoft.Rest 模式）</h2>
    <div class="alert">⚡ 新版使用 <code>Microsoft.Rest</code> 源类型，安装器下载地址会自动改写为 MIRROR 镜像（如 gh-proxy.org），由客户端<b>直连镜像</b>下载，真正解决国内下载慢的问题。</div>
    <div class="steps">
      <div class="step">
        <div class="step-num">1</div>
        <div class="step-body">
          <p>添加镜像源（国内优选推荐）：</p>
          <div class="code-block">
            <pre>winget source add --name winget-cn --arg https://${host} --type Microsoft.Rest</pre>
            <button class="btn" onclick="copyBlock(this)">复制</button>
          </div>
        </div>
      </div>
      <div class="step">
        <div class="step-num">2</div>
        <div class="step-body">
          <p>安装软件（安装器自动走代理加速）：</p>
          <div class="code-block">
            <pre>winget install Git.Git --source winget-cn
winget install Mozilla.Firefox --source winget-cn
winget install SublimeHQ.SublimeText.4 --source winget-cn</pre>
            <button class="btn" onclick="copyBlock(this)">复制</button>
          </div>
        </div>
      </div>
      <div class="step">
        <div class="step-num">3</div>
        <div class="step-body">
          <p>搜索软件包：</p>
          <div class="code-block">
            <pre>winget search notepad --source winget-cn</pre>
            <button class="btn" onclick="copyBlock(this)">复制</button>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Set as default -->
  <div class="card">
    <h2>⭐ 设为默认源（替换官方源）</h2>
    <p style="color:var(--muted);font-size:.875rem;margin-bottom:1rem;">替换后无需加 <code>--source</code> 参数，所有 winget 操作自动走代理。</p>
    <div class="steps">
      <div class="step">
        <div class="step-num">1</div>
        <div class="step-body">
          <p>移除官方默认源：</p>
          <div class="code-block">
            <pre>winget source remove --name winget</pre>
            <button class="btn" onclick="copyBlock(this)">复制</button>
          </div>
        </div>
      </div>
      <div class="step">
        <div class="step-num">2</div>
        <div class="step-body">
          <p>以相同名称添加镜像源：</p>
          <div class="code-block">
            <pre>winget source add --name winget --arg https://${host} --type Microsoft.Rest</pre>
            <button class="btn" onclick="copyBlock(this)">复制</button>
          </div>
        </div>
      </div>
      <div class="step">
        <div class="step-num">3</div>
        <div class="step-body">
          <p>之后直接使用 winget，无需 <code>--source</code>：</p>
          <div class="code-block">
            <pre>winget install Git.Git
winget upgrade --all</pre>
            <button class="btn" onclick="copyBlock(this)">复制</button>
          </div>
          <p class="note">⚠️ 恢复官方源：<code>winget source reset --force</code></p>
        </div>
      </div>
    </div>
  </div>

  <!-- Remove -->
  <div class="card">
    <h2>🔄 移除镜像源</h2>
    <div class="code-block">
      <pre>winget source remove --name winget-cn</pre>
      <button class="btn" onclick="copyBlock(this)">复制</button>
    </div>
  </div>

  <!-- How it works -->
  <div class="card">
    <h2>📡 工作原理</h2>
    <table>
      <thead><tr><th>端点</th><th>说明</th></tr></thead>
      <tbody>
        <tr><td><code>GET /information</code></td><td>源元数据（Microsoft.Rest 协议）</td></tr>
        <tr><td><code>POST /manifestSearch</code></td><td>包搜索，后端为 microsoft/winget-pkgs</td></tr>
        <tr><td><code>GET /packageManifests/{id}</code></td><td>包清单，InstallerUrl 自动重写为代理地址</td></tr>
        <tr><td><code>InstallerUrl</code></td><td>GitHub 链接被改写为 <code>MIRROR/https://github.com/...</code>，由客户端直连镜像下载（不经本 Worker）</td></tr>
      </tbody>
    </table>
  </div>

  <footer>Powered by <a href="https://workers.cloudflare.com" target="_blank">Cloudflare Workers</a> &nbsp;·&nbsp; 数据来源：<a href="https://github.com/microsoft/winget-pkgs" target="_blank">microsoft/winget-pkgs</a></footer>
</div>
<script>
function copyBlock(btn) {
  const pre = btn.closest('.code-block').querySelector('pre');
  navigator.clipboard.writeText(pre.textContent.trim()).then(() => {
    const t = btn.textContent;
    btn.textContent = '已复制';
    setTimeout(() => btn.textContent = t, 1500);
  });
}
</script>
</body>
</html>`;
  return new Response(html, { headers: { "content-type": "text/html;charset=utf-8" } });
}

// ─── Main handler ─────────────────────────────────────────────────────────────

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    const { pathname } = url;
    const mirror = (env.MIRROR || "https://gh-proxy.org").replace(/\/+$/, "");

    // Landing page
    if (pathname === "/" || pathname === "") {
      return landingPage(url.host, mirror);
    }

    // ── Microsoft.Rest API endpoints ────────────────────────────────────────
    // Operational read-out for "is the search broken because the index is
    // missing?" — which otherwise looks identical to "nothing matches that
    // keyword". Fetches with force, so it reports the origin rather than a memo
    // a previous request happened to leave behind.
    if (pathname === "/_index" && request.method === "GET") {
      const index = await getIndex(env, { force: true });
      return Response.json({
        url: env.INDEX_URL ?? null,
        entries: index?.length ?? 0,
        first: index?.[0]?.id ?? null,
        withMoniker: index?.filter((e) => e.m).length ?? 0,
        withTags: index?.filter((e) => e.t).length ?? 0,
      });
    }

    if (pathname === "/information" && request.method === "GET") {
      return handleInformation();
    }
    if (pathname === "/manifestSearch" && request.method === "POST") {
      return handleManifestSearch(request, env);
    }
    // /packageManifests/{id}  or  /packageManifests/{id}/{version}
    const mfMatch = pathname.match(
      /^\/packageManifests\/([^/]+)(?:\/([^/]+))?$/
    );
    if (mfMatch && request.method === "GET") {
      const id = decodeURIComponent(mfMatch[1]);
      // winget passes the version as a query param (?Version=...), not a path
      // segment; honor it so we fetch the exact requested version directly
      // instead of falling back to a rate-limited GitHub API version listing.
      const version =
        (mfMatch[2]
          ? decodeURIComponent(mfMatch[2])
          : url.searchParams.get("Version")) ?? null;
      return handlePackageManifest(id, version, mirror, env);
    }

    // ── This worker is manifest-only. Installer downloads are rewritten to the
    //    mirror (ghproxy) inside handlePackageManifest, so the client fetches
    //    them directly from the mirror. No download-proxy branch is needed. ──
    return new Response("Not found", { status: 404 });
  },
};
