/**
 * Winget Source Proxy Worker — Microsoft.Rest mode
 *
 * Implements a Microsoft.Rest winget source backed by the microsoft/winget-pkgs
 * GitHub repository. Rewrites InstallerUrl values to proxy through this worker
 * so all installer downloads are accelerated (no manifest hash issue — REST
 * sources do not SHA256-verify manifest content).
 *
 * REST API endpoints (for Microsoft.Rest source type):
 *   GET  /information             → source metadata
 *   POST /manifestSearch          → package search (exact ID + keyword)
 *   GET  /packageManifests/{id}   → package manifest with rewritten InstallerUrl
 *
 * Generic installer downloads are NOT proxied: InstallerUrl values are rewritten
 * to the MIRROR and the client fetches them from the mirror directly.
 *
 * Usage:
 *   winget source add --name winget-cn \
 *     --arg https://<your-worker-subdomain>.workers.dev \
 *     --type Microsoft.Rest
 *
 * Configure the installer mirror via the MIRROR env var (wrangler.toml [vars]
 * or a secret). It must accept the path form:
 *   <MIRROR>/https://github.com/owner/repo/...
 * e.g. https://gh-proxy.org
 */
import * as jsyaml from "js-yaml";

// ─── Constants ───────────────────────────────────────────────────────────────

const WINGET_PKGS_API = "https://api.github.com/repos/microsoft/winget-pkgs";
// YAML manifest files. Prefer jsDelivr's CDN (cdn.jsdelivr.net/gh/...@master):
// it is purpose-built for serving repo files, has a global edge cache, and — unlike
// raw.githubusercontent.com — does NOT rate-limit Cloudflare Workers' shared egress
// IPs. A transient 429 from raw.githubusercontent previously returned an empty body
// that the cf cache then pinned for an hour, producing manifests with Installers:[]
// (winget install dies with 0x8a150039). We only fall back to raw.githubusercontent
// if jsDelivr is unreachable.
const JSDLV_MANIFEST_BASE = "https://cdn.jsdelivr.net/gh/microsoft/winget-pkgs@master";
const RAW_MANIFEST_BASE = "https://raw.githubusercontent.com/microsoft/winget-pkgs/master";

// ─── Environment ─────────────────────────────────────────────────────────────

interface Env {
  GITHUB_TOKEN?: string;
  // Mirror used for GitHub-hosted installers, e.g. https://gh-proxy.org
  // Must accept the path form: <MIRROR>/https://github.com/owner/repo/...
  MIRROR?: string;
  // Prebuilt full package index (id + latest version), generated by the
  // build-index Action and served from this repo. Enables complete keyword
  // search without per-query GitHub API calls.
  INDEX_URL?: string;
}

// ─── HTTP helpers ────────────────────────────────────────────────────────────

// Rewrite only GitHub-hosted installer URLs to go through a ghproxy-style
// mirror. Non-GitHub installers keep their original URL (winget downloads them
// directly). The mirror is expected to accept the path form:
//   <MIRROR>/https://github.com/owner/repo/...
// so the client fetches the installer from the mirror, NOT through this worker.
function rewriteInstallerUrl(url: string, mirror: string): string {
  if (!url) return url;
  try {
    const u = new URL(url);
    const isGitHub =
      /github\.com$/.test(u.host) || /githubusercontent\.com$/.test(u.host);
    if (isGitHub) {
      return `${mirror.replace(/\/+$/, "")}/${u.protocol}//${u.host}${u.pathname}${u.search}`;
    }
  } catch { /* leave as-is */ }
  return url;
}

// ─── GitHub helper ────────────────────────────────────────────────────────────
// Only used for directory listing (version enumeration). Responses are cached
// at the CF edge to keep the request volume against api.github.com far below the
// rate limit (60/h unauthenticated — and Cloudflare egress IPs are shared, so
// that budget is not even ours alone; 5000/h with GITHUB_TOKEN).

async function ghFetch(url: string, env: Env): Promise<Response> {
  const headers: Record<string, string> = {
    "User-Agent": "winget-cn-proxy/2.0",
    Accept: "application/vnd.github.v3+json",
  };
  if (env.GITHUB_TOKEN) headers["Authorization"] = `token ${env.GITHUB_TOKEN}`;
  return fetch(url, {
    headers,
    // @ts-ignore: CF Workers cf option for edge-level caching.
    // Errors are cached very briefly rather than at all: a 403 rate-limit must
    // not be pinned (it would make every later search for the same term fail),
    // but replaying it on every request while we are limited just burns the
    // shared upstream budget faster. 60s bounds both.
    cf: {
      cacheEverything: true,
      cacheTtlByStatus: { "200-399": 1800, "400-599": 60 },
    },
  });
}

// Fetch a manifest YAML file, trying jsDelivr first then raw.githubusercontent.
// Returns the text body, or null if every source failed or returned an empty body.
// Error/empty responses are never edge-cached (cacheTtlByStatus 400-599:0) so a
// transient upstream failure can't be pinned for an hour like it could with a
// fixed cacheTtl.
async function fetchManifestFile(
  versionPath: string,
  filename: string
): Promise<string | null> {
  const candidates = [
    `${JSDLV_MANIFEST_BASE}/${versionPath}/${filename}`,
    `${RAW_MANIFEST_BASE}/${versionPath}/${filename}`,
  ];
  for (const url of candidates) {
    try {
      const r = await fetch(url, {
        headers: { "User-Agent": "winget-cn-proxy/2.0" },
        // @ts-ignore — CF Workers cf option for edge caching.
        cf: {
          cacheEverything: true,
          cacheTtlByStatus: { "200-299": 3600, "400-599": 0 },
        },
      });
      if (r.ok) {
        const t = await r.text();
        if (t && t.trim().length) return t;
      }
    } catch {
      // try next candidate
    }
  }
  return null;
}

// ─── Package ID helpers ───────────────────────────────────────────────────────

interface PkgPath {
  firstLetter: string;
  publisher: string;
  packageRest: string;
  basePath: string; // e.g. "manifests/s/SublimeHQ/SublimeText.4"
}

function parsePackageId(id: string): PkgPath {
  const firstLetter = id[0].toLowerCase();
  const dot = id.indexOf(".");
  const publisher = dot >= 0 ? id.slice(0, dot) : id;
  const packageRest = dot >= 0 ? id.slice(dot + 1) : "";
  // Directory path: all dots in the package portion become slashes
  // e.g. SublimeHQ.SublimeText.4 → manifests/s/SublimeHQ/SublimeText/4
  const packageDirPath = packageRest.replace(/\./g, "/");
  return {
    firstLetter,
    publisher,
    packageRest,
    basePath: `manifests/${firstLetter}/${publisher}/${packageDirPath}`,
  };
}

function compareVersions(a: string, b: string): number {
  const norm = (v: string) =>
    v.split(".").map((x) => parseInt(x.replace(/\D/g, "")) || 0);
  const ap = norm(a);
  const bp = norm(b);
  for (let i = 0; i < Math.max(ap.length, bp.length); i++) {
    const d = (ap[i] ?? 0) - (bp[i] ?? 0);
    if (d !== 0) return d;
  }
  return 0;
}

// ─── REST API: GET /information ───────────────────────────────────────────────

function handleInformation(): Response {
  return Response.json({
    Data: {
      SourceIdentifier: "winget-cn",
      ServerSupportedVersions: ["1.0.0", "1.1.0", "1.6.0"],
    },
  });
}

// ─── Keyword search ─────────────────────────────────────────────────────────
// Strategy (in order):
//  1. Full prebuilt index (INDEX_URL): a package list (id + latest version)
//     generated by a GitHub Action and served from the repo. Matched by
//     substring on PackageIdentifier. Fast, no GitHub API calls, and complete
//     for any substring of the id. Limitation (light index): does NOT cover
//     moniker/display-name matches like "vscode".
//  2. Directory enumeration fallback: covers brand-new packages (< index age)
//     and anything the index missed. Uses the GitHub contents API.

// Module-level memo of the parsed index (refreshed hourly). The blob itself is
// also edge-cached via the cf fetch option, so this just avoids re-parsing.
let indexCache: { data: { id: string; v: string }[]; at: number } | null = null;

async function getIndex(env: Env): Promise<{ id: string; v: string }[] | null> {
  if (!env.INDEX_URL) return null;
  const now = Date.now();
  if (indexCache && now - indexCache.at < 3_600_000) return indexCache.data;
  try {
    const resp = await fetch(env.INDEX_URL, {
      headers: { "User-Agent": "winget-cn-proxy/2.0" },
      cf: { cacheEverything: true, cacheTtl: 3600 },
    });
    if (!resp.ok) return indexCache?.data ?? null;
    const text = await resp.text();
    const data = text
      .split("\n")
      .filter((l) => l.trim().length > 0)
      .map((l) => JSON.parse(l) as { id: string; v: string });
    indexCache = { data, at: now };
    return data;
  } catch {
    return indexCache?.data ?? null;
  }
}

// Return a search Data entry for a PackageIdentifier. The prebuilt index is
// consulted first: it knows the package exists and its latest version, which is
// all winget needs to then fetch a manifest. Only a package that is genuinely
// absent from the index (published after the last index build) costs a GitHub
// API call, to enumerate its version directories.
async function lookupPackageId(
  id: string,
  env: Env,
  requestedVersion?: string | null
): Promise<object | null> {
  const { basePath, publisher, packageRest } = parsePackageId(id);
  const index = await getIndex(env);
  const hit =
    index?.find((e) => e.id === id) ??
    index?.find((e) => e.id.toLowerCase() === id.toLowerCase());
  if (hit?.v) {
    const versions = [hit.v];
    if (requestedVersion && requestedVersion !== hit.v) versions.push(requestedVersion);
    return {
      PackageIdentifier: hit.id,
      PackageName: packageRest.replace(/\./g, " "),
      Publisher: publisher,
      Versions: versions.map((v) => ({ PackageVersion: v })),
    };
  }

  const resp = await ghFetch(`${WINGET_PKGS_API}/contents/${basePath}`, env);
  if (!resp.ok) return null;
  const entries = (await resp.json()) as any[];
  const versions = entries
    .filter((e) => e.type === "dir")
    .map((e) => e.name)
    .sort((a, b) => compareVersions(b, a));
  if (versions.length === 0) return null;
  return {
    PackageIdentifier: id,
    PackageName: packageRest.replace(/\./g, " "),
    Publisher: publisher,
    Versions: versions.slice(0, 10).map((v) => ({ PackageVersion: v })),
  };
}

// The enumeration fallback is the ONLY thing that can burn the GitHub API
// budget, so it is bounded hard: at most 1 letter listing + ENUM_PUBLISHERS
// publisher listings + ENUM_PUBLISHERS·ENUM_PACKAGES package listings per cold
// query, each level fetched concurrently. Worst case ≈ 1 + 6 + 36 = 43 calls,
// i.e. usable inside the 60/h unauthenticated budget even in one burst (and
// Cloudflare's shared egress IP means that budget is not ours alone).
const ENUM_PUBLISHERS = 6;
const ENUM_PACKAGES = 6;

// Directory enumeration is keyed off manifests/{first letter}/{Publisher}/…, so
// it can only work for an ASCII-letter keyword. Anything else (digits, CJK,
// empty) must not reach the API at all.
function isEnumerableKeyword(kw: string): boolean {
  return /^[a-z]/.test(kw);
}

// Search results only need the four fields winget's deserializer requires; the
// full display metadata comes later from /packageManifests.
function toSearchResults(matched: Map<string, string>): object[] {
  const out: object[] = [];
  for (const [id, version] of matched) {
    out.push({
      PackageIdentifier: id,
      PackageName: id.split(".").slice(1).join(" "),
      Publisher: id.split(".")[0],
      Versions: [{ PackageVersion: version }],
    });
  }
  return out;
}

// Match quality, lowest number wins. Truncation keeps the best matches.
const P_EXACT = 0;
const P_ID_PREFIX = 1;
const P_NORM_PREFIX = 2;
const P_SUBSTRING = 3;
const P_ABBREVIATION = 4;

// Does `needle` appear as a character subsequence of `hay`? "vlc" is a
// subsequence of "videolanvlc", and winget users type exactly these
// abbreviations. This is the last tier, so it only runs when nothing matched.
// Returns the end position of the tightest match, or -1 when there is none:
// tighter means a better candidate when the tier is capped.
function subsequenceEnd(needle: string, hay: string): number {
  let i = 0;
  for (let j = 0; j < hay.length; j++) {
    if (hay[j] === needle[i]) {
      i++;
      if (i === needle.length) return j;
    }
  }
  return -1;
}

const ABBREVIATION_MIN_LENGTH = 3;
const MAX_KEYWORD_RESULTS = 200;
// Subsequence hits are a weak signal; let them fill the screen but never swamp it.
const MAX_ABBREVIATION_RESULTS = 40;

async function keywordSearch(keyword: string, env: Env): Promise<object[]> {
  const kw = keyword.toLowerCase().trim();
  if (!kw) return [];

  // 1) Full prebuilt index, in five tiers of decreasing precision:
  //      exact id → id prefix → normalized prefix → substring → abbreviation.
  //    Answering here is what keeps a query off api.github.com. `winget search
  //    vscode` used to reach enumeration because "vscode" is neither a substring
  //    of nor a prefix of "microsoftvisualstudiocode"; the abbreviation tier
  //    covers it locally.
  const index = await getIndex(env);
  if (index && index.length) {
    const nkw = normalizeTerm(kw);
    const best = new Map<string, { v: string; p: number; t: number }>();
    const consider = (id: string, v: string, p: number, t: number) => {
      const cur = best.get(id);
      if (!cur || p < cur.p || (p === cur.p && t < cur.t)) best.set(id, { v, p, t });
    };
    for (const e of index) {
      if (!e.v) continue; // never emit empty Versions — winget rejects it (0x8a150039)
      const lowerId = e.id.toLowerCase();
      const nid = nkw.length > 1 ? normalizeTerm(e.id) : "";
      if (lowerId === kw) consider(e.id, e.v, P_EXACT, lowerId.length);
      else if (lowerId.startsWith(kw)) consider(e.id, e.v, P_ID_PREFIX, lowerId.length);
      else if (nid && nid.startsWith(nkw)) consider(e.id, e.v, P_NORM_PREFIX, nid.length);
      else if (lowerId.includes(kw) || (nid && nid.includes(nkw))) {
        // earlier match position = more likely the package the user meant
        const pos = Math.max(0, lowerId.indexOf(kw));
        consider(e.id, e.v, P_SUBSTRING, pos * 1000 + lowerId.length);
      } else if (nkw.length >= ABBREVIATION_MIN_LENGTH && nid) {
        const end = subsequenceEnd(nkw, nid);
        if (end >= 0) consider(e.id, e.v, P_ABBREVIATION, end);
      }
    }
    if (best.size) {
      const ranked = [...best.entries()].sort(
        (a, b) => a[1].p - b[1].p || a[1].t - b[1].t || a[0].localeCompare(b[0])
      );
      // The abbreviation tier is a weak signal; cap it separately so a short
      // keyword cannot flood the result list with subsequence noise.
      const kept = new Map<string, string>();
      let abbrevKept = 0;
      for (const [id, e] of ranked) {
        if (kept.size >= MAX_KEYWORD_RESULTS) break;
        if (e.p === P_ABBREVIATION) {
          if (abbrevKept >= MAX_ABBREVIATION_RESULTS) continue;
          abbrevKept++;
        }
        kept.set(id, e.v);
      }
      console.log(
        `keywordSearch: index hit, matched=${best.size} (${ranked[0][1].p <= P_SUBSTRING ? "direct" : "abbreviation"}), returned=${kept.size} for "${keyword}"`
      );
      return toSearchResults(kept);
    }
    console.log(`keywordSearch: index miss for "${keyword}" — falling back to enumeration`);
  }

  if (!isEnumerableKeyword(kw)) {
    console.log(`keywordSearch: "${keyword}" is not enumerable (needs an ASCII first letter)`);
    return [];
  }
  const letter = kw[0];

  // 2) Publisher-directory enumeration, bounded and concurrent.
  const lresp = await ghFetch(`${WINGET_PKGS_API}/contents/manifests/${letter}`, env);
  if (!lresp.ok) {
    console.log(`keywordSearch: letter list failed status ${lresp.status} (letter=${letter})`);
    return [];
  }
  const dirs = (await lresp.json()) as any[];
  const pubs = (dirs ?? []).filter(
    (d) => d.type === "dir" && d.name.toLowerCase().includes(kw)
  ).slice(0, ENUM_PUBLISHERS);
  console.log(`keywordSearch: letter=${letter}, dirs=${(dirs ?? []).length}, probingPubs=${pubs.length}`);

  const pkgLists = await Promise.all(
    pubs.map(async (pub) => {
      const r = await ghFetch(
        `${WINGET_PKGS_API}/contents/manifests/${letter}/${pub.name}`, env);
      if (!r.ok) return [];
      const entries = ((await r.json()) as any[]).filter((p) => p.type === "dir");
      return entries.slice(0, ENUM_PACKAGES).map((p) => ({ pub: pub.name, pkg: p.name }));
    })
  );

  const wanted = new Map<string, string>();
  for (const list of pkgLists) {
    for (const { pub, pkg } of list) {
      const id = `${pub}.${pkg}`;
      if (!wanted.has(id)) wanted.set(id, `${letter}/${pub}/${pkg}`);
    }
  }

  const versionLists = await Promise.all(
    [...wanted.entries()].map(async ([id, dir]) => {
      const r = await ghFetch(`${WINGET_PKGS_API}/contents/manifests/${dir}`, env);
      if (!r.ok) return null;
      const vers = ((await r.json()) as any[])
        .filter((e) => e.type === "dir")
        .map((e) => e.name)
        .sort(compareVersions)
        .reverse();
      return vers.length ? { id, version: vers[0] } : null;
    })
  );

  const seen = new Map<string, string>();
  for (const v of versionLists) {
    if (v && !seen.has(v.id)) seen.set(v.id, v.version);
  }

  return toSearchResults(seen);
}

// winget's ProductCode is "<PackageIdentifier>_<sourceId>", e.g.
// "yt-dlp.yt-dlp_microsoft.winget.source_8wekyb3d8bbwe". The source id is the
// source that *declared* the dependency (the official one), so for dependency
// resolution it is meaningless to us. Strip it to recover the bare
// PackageIdentifier we can look up directly.
function stripProductCodeSuffix(kw: string): string {
  const known = kw.lastIndexOf("_microsoft.winget.source_");
  if (known > 0) return kw.slice(0, known);
  // Generic fallback: "<id.with.dot>_<sourceToken>"
  const m = kw.match(/^([A-Za-z0-9.-]+\.[A-Za-z0-9.-]+?)_[A-Za-z0-9._-]+$/);
  if (m) return m[1];
  return kw;
}

// Normalize a search term the way winget normalizes PackageName/Publisher for
// the NormalizedPackageNameAndPublisher match field: lowercase, drop every
// non-alphanumeric char ("yt-dlp" -> "ytdlp").
function normalizeTerm(s: string): string {
  return (s ?? "").toLowerCase().replace(/[^a-z0-9]/g, "");
}

// ─── REST API: POST /manifestSearch ──────────────────────────────────────────

async function handleManifestSearch(
  request: Request,
  env: Env
): Promise<Response> {
  let body: any;
  try {
    body = await request.json();
  } catch {
    return Response.json({ Data: [] });
  }

  // Debug: log exact request body from winget
  console.log("manifestSearch body:", JSON.stringify(body));

  const filters: any[] = body?.Filters ?? [];
  const inclusions: any[] = body?.Inclusions ?? [];
  const query = body?.Query;

  // ── Case 0: dependency resolution (ProductCode) ────────────────────────────
  // When winget resolves a package's dependencies it queries every source by
  // ProductCode ("<id>_microsoft.winget.source_8wekyb3d8bbwe") and by
  // NormalizedPackageNameAndPublisher. Our index is keyed by PackageIdentifier,
  // so strip the ProductCode source suffix to recover the exact id and look it
  // up directly. This makes dependency search hit instead of returning empty.
  const productCode = inclusions.find(
    (f) => f.PackageMatchField === "ProductCode"
  )?.RequestMatch?.KeyWord;
  if (productCode) {
    // winget LOWERCASES the PackageIdentifier inside a ProductCode, while the
    // GitHub directory path is case-sensitive ("yt-dlp.FFmpeg" not "...ffmpeg").
    // lookupPackageId resolves the canonical casing from the index.
    const rawId = stripProductCodeSuffix(productCode);
    console.log("manifestSearch: productCode -> id:", productCode, "->", rawId);
    if (rawId && rawId.includes(".")) {
      const entry = await lookupPackageId(rawId, env);
      if (entry) {
        const result = { Data: [entry] };
        console.log("manifestSearch response (productCode):", JSON.stringify(result));
        return Response.json(result);
      }
    }
  }

  // ── Case 1: PackageIdentifier filter/inclusion ───────────────────────────
  // Only treat as a real id lookup when the value contains a dot. winget
  // sometimes sends a bare keyword (e.g. "HandBrake") under the
  // PackageIdentifier match field; parsing that as an id yields an empty
  // PackageName and a bogus basePath, making winget reject the whole search
  // (0x8a150039 "Missing required package fields").
  const allCriteria = [...filters, ...inclusions];
  const idFilter = allCriteria.find(
    (f) =>
      f.PackageMatchField === "PackageIdentifier" &&
      (f.RequestMatch?.MatchType === "Exact" ||
        f.RequestMatch?.MatchType === "CaseInsensitive") &&
      (f.RequestMatch?.KeyWord ?? "").includes(".")
  );
  if (idFilter) {
    const id: string = idFilter.RequestMatch.KeyWord;
    console.log("manifestSearch: looking up package id:", id);
    const entry = await lookupPackageId(id, env);
    if (entry) {
      const result = { Data: [entry] };
      console.log("manifestSearch response:", JSON.stringify(result));
      return Response.json(result);
    }
    // Not found (or rate-limited) -> fall through to keyword search below.
  }

  // ── Case 2: keyword search ───────────────────────────────────────────────
  // winget's `upgrade <word>` sends the term as name-like Inclusions
  // (PackageName / Moniker / Publisher / PackageIdentifier) rather than a Query.
  const keyword: string | undefined =
    query?.KeyWord ??
    allCriteria.find(
      (c) =>
        [
          "PackageName",
          "Moniker",
          "Publisher",
          "PackageIdentifier",
          "NormalizedPackageNameAndPublisher",
        ].includes(c.PackageMatchField) && c.RequestMatch?.KeyWord
    )?.RequestMatch?.KeyWord;
  if (keyword) {
    // If keyword looks like a PackageIdentifier (Publisher.Package), try direct lookup first
    if (/^[A-Za-z0-9_-]+\.[A-Za-z0-9._-]+$/.test(keyword)) {
      const entry = await lookupPackageId(keyword, env);
      if (entry) {
        return Response.json({ Data: [entry] });
      }
    }

    // Keyword search via publisher-directory enumeration (GitHub code search is
    // unreliable for winget-pkgs, so we don't use it).
    const results = await keywordSearch(keyword, env);
    if (results.length) {
      return Response.json({ Data: results });
    }
  }

  console.log("manifestSearch: no results (empty Data)");
  return Response.json({ Data: [] });
}

// ─── REST API: GET /packageManifests/{id}[/{version}] ────────────────────────

async function handlePackageManifest(
  id: string,
  requestedVersion: string | null,
  mirror: string,
  env: Env
): Promise<Response> {
  const { publisher, packageRest, basePath } = parsePackageId(id);

  let version: string;
  if (requestedVersion) {
    version = requestedVersion;
  } else {
    // Resolve the latest version. Prefer the prebuilt index (no GitHub API call,
    // no rate limit). Fall back to the GitHub contents API only if the package
    // isn't in the index (brand-new, or index miss).
    const index = await getIndex(env);
    const hit = index?.find((e) => e.id === id);
    if (hit?.v) {
      version = hit.v;
    } else {
      const resp = await ghFetch(`${WINGET_PKGS_API}/contents/${basePath}`, env);
      if (!resp.ok) {
        return Response.json(
          { ErrorCode: 404, ErrorMessage: `Package not found: ${id}` },
          { status: 404 }
        );
      }
      const entries = (await resp.json()) as any[];
      const versions = entries
        .filter((e) => e.type === "dir")
        .map((e) => e.name)
        .sort((a, b) => compareVersions(b, a));
      if (versions.length === 0) {
        return Response.json(
          { ErrorCode: 404, ErrorMessage: `No versions found: ${id}` },
          { status: 404 }
        );
      }
      version = versions[0];
    }
  }

  const versionPath = `${basePath}/${version}`;

  // Fetch installer YAML: try the multi-file ".installer.yaml" first, then the
  // single combined ".yaml". Both are resolved via fetchManifestFile (jsDelivr
  // prefer red, raw.githubusercontent fallback).
  const installerYaml =
    (await fetchManifestFile(versionPath, `${id}.installer.yaml`)) ??
    (await fetchManifestFile(versionPath, `${id}.yaml`));

  if (!installerYaml) {
    return Response.json(
      { ErrorCode: 404, ErrorMessage: `Manifest not found: ${id}@${version}` },
      { status: 404 }
    );
  }

  // Fetch locale YAML for display metadata (optional; null if absent).
  const localeYaml = await fetchManifestFile(
    versionPath,
    `${id}.locale.en-US.yaml`
  );

  // Parse YAMLs
  let installerDoc: any = {};
  let localeDoc: any = {};
  try {
    installerDoc = (jsyaml.load(installerYaml) as any) ?? {};
  } catch { /* ignore parse errors */ }
  try {
    if (localeYaml) localeDoc = (jsyaml.load(localeYaml) as any) ?? {};
  } catch { /* ignore */ }

  // Build installers list with rewritten InstallerUrl
  const rawInstallers: any[] = Array.isArray(installerDoc.Installers)
    ? installerDoc.Installers
    : [];

  // Package-level InstallerType / NestedInstallerType / Dependencies must be
  // propagated to each installer. winget-pkgs stores these at the package level
  // (root of the installer YAML), while each installer entry often omits them;
  // winget's REST deserializer requires InstallerType on every installer and
  // surfaces Dependencies (e.g. "依赖项") from the installer object.
  const installers = rawInstallers.map((inst) => {
    const out: any = { ...inst };
    if (!out.InstallerType && installerDoc.InstallerType) {
      out.InstallerType = installerDoc.InstallerType;
    }
    if (!out.NestedInstallerType && installerDoc.NestedInstallerType) {
      out.NestedInstallerType = installerDoc.NestedInstallerType;
    }
    if (!out.Dependencies && installerDoc.Dependencies) {
      out.Dependencies = installerDoc.Dependencies;
    }
    // Canonicalize portable installers. A portable package is a zip that is
    // extracted and registered; the top-level InstallerType must be "portable"
    // and the nested type the archive ("zip"). Some manifests store the
    // inverted pair (InstallerType: zip / NestedInstallerType: portable), which
    // is an inconsistent combination winget's REST deserializer rejects.
    if (out.NestedInstallerType === "portable") {
      out.NestedInstallerType = "zip";
      if (out.InstallerType !== "portable") out.InstallerType = "portable";
    }
    if (out.InstallerUrl) {
      out.InstallerUrl = rewriteInstallerUrl(out.InstallerUrl, mirror);
    }
    return out;
  });

  // Build DefaultLocale by transparently passing through every field from the
  // manifest's locale YAML (Moniker, Author, PublisherSupportUrl, PrivacyUrl,
  // PackageUrl, Tags, ReleaseNotes, ReleaseNotesUrl, Documentations, Agreements,
  // Description, ...). The winget REST DefaultLocale schema accepts these as
  // optional members; only a hardcoded subset was mapped before, which is why
  // `winget show` looked sparse next to the official source. Drop the
  // YAML-only wrapper keys that have no place in the REST DefaultLocale object.
  const LOCALE_OMIT = new Set([
    "PackageIdentifier",
    "PackageVersion",
    "ManifestType",
    "ManifestVersion",
  ]);
  const defaultLocale: any = {};
  if (localeDoc && Object.keys(localeDoc).length) {
    defaultLocale.PackageLocale = localeDoc.PackageLocale ?? "en-US";
    for (const [k, v] of Object.entries(localeDoc)) {
      if (!LOCALE_OMIT.has(k)) defaultLocale[k] = v;
    }
  } else {
    // Fallback when the locale yaml is unavailable: only the required fields.
    defaultLocale.PackageLocale = "en-US";
    defaultLocale.Publisher = installerDoc?.Publisher ?? publisher;
    defaultLocale.PublisherUrl = installerDoc?.PublisherUrl ?? "";
    defaultLocale.PackageName =
      installerDoc?.PackageName ?? `${publisher} ${packageRest}`;
    defaultLocale.ShortDescription =
      installerDoc?.ShortDescription ?? installerDoc?.Description ?? "";
    defaultLocale.License = installerDoc?.License ?? "";
    defaultLocale.LicenseUrl = installerDoc?.LicenseUrl ?? "";
    defaultLocale.Copyright = installerDoc?.Copyright ?? "";
  }

  return Response.json({
    Data: {
      PackageIdentifier: id,
      // winget's Microsoft.Rest packageManifest contract requires PackageName
      // and Publisher at the top-level Data object (not only inside
      // DefaultLocale). Omitting them makes winget reject the whole manifest
      // with 0x8a150039 "REST source returned invalid data".
      PackageName:
        localeDoc?.PackageName ??
        installerDoc?.PackageName ??
        `${publisher} ${packageRest}`,
      Publisher: localeDoc?.Publisher ?? installerDoc?.Publisher ?? publisher,
      ShortDescription:
        localeDoc?.ShortDescription ?? installerDoc?.Description ?? "",
      Versions: [
        {
          PackageVersion: version,
          DefaultLocale: defaultLocale,
          Installers: installers,
          Locales: [],
        },
      ],
    },
  });
}

// ─── Landing page ─────────────────────────────────────────────────────────────

function landingPage(host: string, mirror: string): Response {
  const html = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Winget 镜像代理</title>
<style>
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  :root {
    --bg: #0d1117; --surface: #161b22; --card: #21262d; --border: #30363d;
    --text: #e6edf3; --muted: #8b949e; --accent: #58a6ff;
    --green: #3fb950; --yellow: #e3b341; --radius: 8px;
  }
  body { background: var(--bg); color: var(--text); font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; min-height: 100vh; padding: 2rem 1rem; }
  .container { max-width: 860px; margin: 0 auto; }
  header { text-align: center; padding: 2rem 0 2.5rem; }
  header h1 { font-size: 2rem; font-weight: 700; display: flex; align-items: center; justify-content: center; gap: .6rem; }
  header p { color: var(--muted); margin-top: .6rem; font-size: .95rem; }
  .badge-row { display: flex; gap: .75rem; flex-wrap: wrap; justify-content: center; margin-top: .75rem; font-size: .85rem; }
  .badge { background: var(--card); border: 1px solid var(--border); border-radius: 6px; padding: .3rem .75rem; }
  .card { background: var(--surface); border: 1px solid var(--border); border-radius: var(--radius); padding: 1.5rem; margin-bottom: 1.5rem; }
  .card h2 { font-size: 1rem; font-weight: 600; margin-bottom: 1rem; color: var(--accent); }
  .steps { display: flex; flex-direction: column; gap: .75rem; }
  .step { display: flex; gap: .75rem; }
  .step-num { width: 22px; height: 22px; border-radius: 50%; background: rgba(88,166,255,.2); color: var(--accent); font-size: .75rem; font-weight: 700; display: flex; align-items: center; justify-content: center; flex-shrink: 0; margin-top: 2px; }
  .step-body { flex: 1; }
  .step-body p { font-size: .875rem; color: var(--muted); margin-bottom: .4rem; }
  .code-block { background: var(--bg); border: 1px solid var(--border); border-radius: 6px; padding: .65rem .9rem; font-family: "SFMono-Regular", Consolas, monospace; font-size: .82rem; display: flex; gap: .5rem; align-items: flex-start; }
  .code-block pre { flex: 1; margin: 0; white-space: pre-wrap; word-break: break-all; color: var(--green); }
  .btn { background: transparent; color: var(--muted); border: 1px solid var(--border); border-radius: 6px; padding: .35rem .75rem; font-size: .8rem; cursor: pointer; white-space: nowrap; }
  .btn:hover { color: var(--accent); border-color: var(--accent); }
  .note { font-size: .78rem; color: var(--muted); margin-top: .4rem; }
  .alert { background: rgba(255,166,0,.08); border: 1px solid rgba(255,166,0,.3); border-radius: 6px; padding: .65rem .9rem; font-size: .85rem; color: var(--yellow); margin-bottom: 1rem; }
  table { width: 100%; border-collapse: collapse; font-size: .875rem; }
  th { text-align: left; color: var(--muted); font-weight: 500; padding: .5rem .75rem; border-bottom: 1px solid var(--border); }
  td { padding: .55rem .75rem; border-bottom: 1px solid var(--border); }
  tr:last-child td { border-bottom: none; }
  code { background: rgba(110,118,129,.15); border-radius: 4px; padding: .15em .45em; font-family: "SFMono-Regular", Consolas, monospace; font-size: .85em; }
  footer { text-align: center; color: var(--muted); font-size: .8rem; padding: 2rem 0 1rem; }
  footer a { color: var(--accent); text-decoration: none; }
</style>
</head>
<body>
<div class="container">
  <header>
    <h1>📦 Winget 镜像代理</h1>
    <p>基于 Cloudflare Workers 的自建 winget 源（Microsoft.Rest）· 自动将 GitHub 安装包地址改写为国内镜像（gh-proxy 等），安装器由客户端直连镜像下载，国内拉取飞快。</p>
    <div class="badge-row">
      <span class="badge">🌐 镜像源地址：<code>${host}</code></span>
      <span class="badge">🇨🇳 安装器镜像：<code>${mirror}</code></span>
    </div>
  </header>

  <!-- Quick Start -->
  <div class="card">
    <h2>🚀 快速开始（推荐：Microsoft.Rest 模式）</h2>
    <div class="alert">⚡ 新版使用 <code>Microsoft.Rest</code> 源类型，安装器下载地址会自动改写为 MIRROR 镜像（如 gh-proxy.org），由客户端<b>直连镜像</b>下载，真正解决国内下载慢的问题。</div>
    <div class="steps">
      <div class="step">
        <div class="step-num">1</div>
        <div class="step-body">
          <p>添加镜像源（国内优选推荐）：</p>
          <div class="code-block">
            <pre>winget source add --name winget-cn --arg https://${host} --type Microsoft.Rest</pre>
            <button class="btn" onclick="copyBlock(this)">复制</button>
          </div>
        </div>
      </div>
      <div class="step">
        <div class="step-num">2</div>
        <div class="step-body">
          <p>安装软件（安装器自动走代理加速）：</p>
          <div class="code-block">
            <pre>winget install Git.Git --source winget-cn
winget install Mozilla.Firefox --source winget-cn
winget install SublimeHQ.SublimeText.4 --source winget-cn</pre>
            <button class="btn" onclick="copyBlock(this)">复制</button>
          </div>
        </div>
      </div>
      <div class="step">
        <div class="step-num">3</div>
        <div class="step-body">
          <p>搜索软件包：</p>
          <div class="code-block">
            <pre>winget search vscode --source winget-cn</pre>
            <button class="btn" onclick="copyBlock(this)">复制</button>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Set as default -->
  <div class="card">
    <h2>⭐ 设为默认源（替换官方源）</h2>
    <p style="color:var(--muted);font-size:.875rem;margin-bottom:1rem;">替换后无需加 <code>--source</code> 参数，所有 winget 操作自动走代理。</p>
    <div class="steps">
      <div class="step">
        <div class="step-num">1</div>
        <div class="step-body">
          <p>移除官方默认源：</p>
          <div class="code-block">
            <pre>winget source remove --name winget</pre>
            <button class="btn" onclick="copyBlock(this)">复制</button>
          </div>
        </div>
      </div>
      <div class="step">
        <div class="step-num">2</div>
        <div class="step-body">
          <p>以相同名称添加镜像源：</p>
          <div class="code-block">
            <pre>winget source add --name winget --arg https://${host} --type Microsoft.Rest</pre>
            <button class="btn" onclick="copyBlock(this)">复制</button>
          </div>
        </div>
      </div>
      <div class="step">
        <div class="step-num">3</div>
        <div class="step-body">
          <p>之后直接使用 winget，无需 <code>--source</code>：</p>
          <div class="code-block">
            <pre>winget install Git.Git
winget upgrade --all</pre>
            <button class="btn" onclick="copyBlock(this)">复制</button>
          </div>
          <p class="note">⚠️ 恢复官方源：<code>winget source reset --force</code></p>
        </div>
      </div>
    </div>
  </div>

  <!-- Remove -->
  <div class="card">
    <h2>🔄 移除镜像源</h2>
    <div class="code-block">
      <pre>winget source remove --name winget-cn</pre>
      <button class="btn" onclick="copyBlock(this)">复制</button>
    </div>
  </div>

  <!-- How it works -->
  <div class="card">
    <h2>📡 工作原理</h2>
    <table>
      <thead><tr><th>端点</th><th>说明</th></tr></thead>
      <tbody>
        <tr><td><code>GET /information</code></td><td>源元数据（Microsoft.Rest 协议）</td></tr>
        <tr><td><code>POST /manifestSearch</code></td><td>包搜索，后端为 microsoft/winget-pkgs</td></tr>
        <tr><td><code>GET /packageManifests/{id}</code></td><td>包清单，InstallerUrl 自动重写为代理地址</td></tr>
        <tr><td><code>InstallerUrl</code></td><td>GitHub 链接被改写为 <code>MIRROR/https://github.com/...</code>，由客户端直连镜像下载（不经本 Worker）</td></tr>
      </tbody>
    </table>
  </div>

  <footer>Powered by <a href="https://workers.cloudflare.com" target="_blank">Cloudflare Workers</a> &nbsp;·&nbsp; 数据来源：<a href="https://github.com/microsoft/winget-pkgs" target="_blank">microsoft/winget-pkgs</a></footer>
</div>
<script>
function copyBlock(btn) {
  const pre = btn.closest('.code-block').querySelector('pre');
  navigator.clipboard.writeText(pre.textContent.trim()).then(() => {
    const t = btn.textContent;
    btn.textContent = '已复制';
    setTimeout(() => btn.textContent = t, 1500);
  });
}
</script>
</body>
</html>`;
  return new Response(html, { headers: { "content-type": "text/html;charset=utf-8" } });
}

// ─── Main handler ─────────────────────────────────────────────────────────────

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    const { pathname } = url;
    const mirror = (env.MIRROR || "https://gh-proxy.org").replace(/\/+$/, "");

    // Landing page
    if (pathname === "/" || pathname === "") {
      return landingPage(url.host, mirror);
    }

    // ── Microsoft.Rest API endpoints ────────────────────────────────────────
    if (pathname === "/information" && request.method === "GET") {
      return handleInformation();
    }
    // Debug: echo request body back (temporary, for diagnosing winget request format)
    if (pathname === "/debug/echo" && request.method === "POST") {
      const body = await request.text();
      return new Response(body, { headers: { "content-type": "application/json" } });
    }
    if (pathname === "/manifestSearch" && request.method === "POST") {
      return handleManifestSearch(request, env);
    }
    // /packageManifests/{id}  or  /packageManifests/{id}/{version}
    const mfMatch = pathname.match(
      /^\/packageManifests\/([^/]+)(?:\/([^/]+))?$/
    );
    if (mfMatch && request.method === "GET") {
      const id = decodeURIComponent(mfMatch[1]);
      // winget passes the version as a query param (?Version=...), not a path
      // segment; honor it so we fetch the exact requested version directly
      // instead of falling back to a rate-limited GitHub API version listing.
      const version =
        (mfMatch[2]
          ? decodeURIComponent(mfMatch[2])
          : url.searchParams.get("Version")) ?? null;
      return handlePackageManifest(id, version, mirror, env);
    }

    // ── This worker is manifest-only. Installer downloads are rewritten to the
    //    mirror (ghproxy) inside handlePackageManifest, so the client fetches
    //    them directly from the mirror. No download-proxy branch is needed. ──
    return new Response("Not found", { status: 404 });
  },
};
